### ISSUE TITLE
Split out creating/mounting RAMDisk into a separate library

### ISSUE THREAD

**Issue by agilgur5** [shellscape/webpack-plugin-ramdisk#3]
### Feature Use Case

They're aren't many Node libraries for RAMDisks out there and I assume you created your own solution because the others didn't suffice(?)

I'd like to use a RAMDisk for testing a library that outputs files, i.e. in https://github.com/jaredpalmer/tsdx/issues/289#issuecomment-584458001 . I believe MPL should be ok to use in TSDX as a dev dependency (though in prod I'm not sure it'd be compatible with MIT, but I'm quite rusty on my license/copyright law)

## Alternatives Considered

`node-ramdisk` appears to be a bit harder to use.
`memfs` just replaces the `fs` library, but not the actual system paths. Would be great to use `memfs` for this purpose, but I think that'd only be possible in a single-process testing set-up which unfortunately doesn't currently work for TSDX's test set-up at least. There might be some other gotchas there too.
If you know of anything else relevant, would be great to hear about it! I wasn't able to find much.

### Feature Proposal

Create a separate RAMDisk package that's used by this plugin.

**Comment by shellscape** [comment]
Could you just import from https://github.com/shellscape/webpack-plugin-ramdisk/blob/master/lib/ramdisk.js? You're also welcome to fork the code and create a lib from just that file (hopefully crediting the author 😄 ). I don't have a daily need for a separate ramdisk package, so I'm not likely to create one, but I do appreciate you taking the time to create the issue. Sorry it took so long for me to address it.
